branch: master
require:
  - $(this-folder)/../readme.azure.noprofile.md
  - $(repo)/specification/databricks/resource-manager/readme.md
try-require:
  - $(repo)/specification/databricks/resource-manager/readme.powershell.md

module-version: 1.2.0
title: BSN.IpTables.Cli
subject-prefix: $(service-name)

inlining-threshold: 100

tag: v1
resourcegroup-append: true
identity-correction-for-post: true
nested-object-to-string: true