branch: master

module-version: 1.2.0
title: BSN.IpTables.Cli
subject-prefix: $(service-name)

inlining-threshold: 100

tag: v1
input-file: ./swagger.json
powershell: true

use:
  - '@autorest/powershell@4.0.657'

namespace: BSN.IpTables.V1
verbose: true
resourcegroup-append: true
identity-correction-for-post: true
nested-object-to-string: true
azure-arm: false
azure-validator: false
