version: '3.4'

services:
  bsn.iptables.api:
    image: resaa.ir/iptables-api:0.1.0
    container_name: ip-tables
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - TZ=Asia/Tehran
      - AUTO_MIGRATE=true
    build:
      context: .
      dockerfile: Source/BSN.IpTables.Api/Dockerfile
