FROM mcr.microsoft.com/dotnet/sdk:6.0
RUN mkdir /usr/local/temp

RUN wget https://aka.ms/getvsdbgsh && \
    sh getvsdbgsh -v latest  -l /vsdbg

RUN apt-get update && apt-get install iptables -y

# For adding sudo inside docker https://stackoverflow.com/a/48329093/1539100

RUN apt-get update \
 && apt-get install -y build-essential libxtables-dev libip6tc-dev \
 libip4tc-dev libiptc-dev libnl-3-dev libnl-3-200 libnetfilter-conntrack3 libnfnetlink-dev libnfnetlink0 libpcap0.8 libpcap0.8-dev sudo

RUN adduser --disabled-password --gecos '' docker
RUN adduser docker sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER docker